context("Resolving SS type to numeric")

test_that("SS types can be specified as numeric, numeral, character", {
  expect_identical(supernova:::resolve_type(1), 1)
  expect_identical(supernova:::resolve_type("1"), 1)
  expect_identical(supernova:::resolve_type("I"), 1)
  expect_identical(supernova:::resolve_type("sequential"), 1)
  expect_identical(supernova:::resolve_type(2), 2)
  expect_identical(supernova:::resolve_type("2"), 2)
  expect_identical(supernova:::resolve_type("II"), 2)
  expect_identical(supernova:::resolve_type("hierarchical"), 2)
  expect_identical(supernova:::resolve_type(3), 3)
  expect_identical(supernova:::resolve_type("3"), 3)
  expect_identical(supernova:::resolve_type("III"), 3)
  expect_identical(supernova:::resolve_type(" iIi "), 3)
  expect_identical(supernova:::resolve_type("orthogonal"), 3)
})
